const ALL_FRIEND = 'ALL_FRIEND'
const REQUEST_FRIEND = 'REQUEST_FRIEND'
const FIND_FRIEND = 'FIND_FRIEND'
const PENDING_FRIEND = 'PENGING_FRIEND'

export { ALL_FRIEND, REQUEST_FRIEND, FIND_FRIEND , PENDING_FRIEND}